name: Test2

on:
  issues:
    types: [opened, closed, reopened, deleted]

jobs:
  test2:
    runs-on: ubuntu-latest

    permissions:
          issues: read

    steps:
      - name: read
        run: echo "Issue title\n$TITLE"; echo "Issue body\n$BODY"; echo "Issue id\n$ID"
        env:
          TITLE: ${{ github.event.issue.title }}
          BODY: ${{ github.event.issue.body }}
          ID: ${{ github.event.issue.id }}
          STATE: ${{ github.event.issue.state }}
