name: Test2

on:
  issues:
    types: [opened, closed, reopened, deleted]

jobs:
  test2:
    runs-on: ubuntu-latest

    permissions:
          contents: read

    steps:
      - name: read
        run: echo "Issue title ${{ github.event.comment.body }}"
