name: Test2

on:
  issues:
    types: [opened, closed, reopened, deleted]

jobs:
  test2:
    runs-on: ubuntu-latest

    permissions:
          issues: read

    steps:
      - name: read
        run: echo "Issue title $TITLE"; echo "Issue body $BODY"
        env:
          TITLE: ${{ github.event.issue.title }}
          BODY: ${{ github.event.issue.body }}
